# Generated by Django 6.0.5 on 2026-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('release_year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Placeholder average rating until user ratings are implemented.', max_digits=3)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
